#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 2360aa9e-b003-4dc1-a081-6d0d73b83fdc
# Source File: C:\Users\Jim\Google Drive\PowerShell Studio\Projects\Astra Assist\Astra Assist.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
9AEAAB+LCAAAAAAABACFkV1LwzAUhu8H+w+h91nTVeaELjAZlV34wTq8ldPm1EWzpiTpZP/eaNOx
oeLdecib5+Uk2QYrfUBzXIEDPh4Rkj0Z/YaV+waPz2is1A2fTlgWDxDOcqlwveLTdMYAbpCWjKX0
SlQJBTZP6EwwcZ2W87QWVRaHcLgaWrbHFrkXn+Mg10r4OhKft9kAAcltJ5VYRCzihQPjunbSWtt3
/ZUkxQ4M+nFrOozIBms02FSYd03l/HKLaN0c9DvSO6VLUC+tTSLez9bbk3/sv/iKnf6g9yCbXJu9
99URH8gL6wthD/2ap2fp6dHIV9mA+go8wB750joDZGmttM6LWh/O4h+p8SiLL375E1OddFL0AQAA#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.136
     Generated on:       3/14/2017 10:42 AM
     Generated by:       Jim
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2017
#>



#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
2gMAAB+LCAAAAAAABAC9k0tLAzEQgO+C/yH0vGR33a5rIbsglV4EFVfUazadLcE8yiRpyb+3rVJF
QaGHMJd5MPMxL/YIwm4A4w33nOwUJ61pJxe0nHTnZ4Swe5QrabhaSAV3XEPXe44+rOnaOZb/ih5y
rp0DPSgJ7mB/eWKnnbCo5JCR50/WlBZ7ycg8KB8QWgPBI1cZeQi7GuIW4pN9A9MOTcNrUV+Ws2oK
xdWM5ceqPyl9dB50CgZ9kWZpt44uLGqXhLjfVBoQ8q00q1NYRTXWYzOW5bIueMX/Z71qlaSnuUVI
MzyJILzF2ANupICTbuPvMR7Nj0dj+fdf7t4BtbYVHtoDAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	$roomwatermark = "DSC 251"
	$datewatermark = "YYYY-MM-DD"
	$timewatermark = "HH:MM:AM"
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	function Convert-Minutes ($time)
	{
		$seconds = ($time * 60)
		$hours = 0
		$minutes = 0
		While ($seconds -ge 60)
		{
			$seconds = ($seconds - 60)
			$minutes++
			IF ($minutes -eq 60)
			{
				$hours++
				$minutes = 0
			}
		}
		If ($hours -ge "12")
		{
			$afternoon = "PM"
			IF ($hours -ne "12")
			{
				$hours = $hours - 12	
			}
		}
		Else { $afternoon = "AM" }
		$hours = $hours.ToString()
		$minutes = $minutes.ToString()
		If ($minutes.Length -eq 1)
		{
			$minutes = $minutes + "0"	
		}
		$time = $hours + ":" + $minutes + " " + $afternoon
		Return $time
	}
	
	function Get-CurrentTime
	{
		[string]$syst = Get-Date -DisplayHint Time
		[int]$timelen = $syst.Length
		$syst = $syst.Substring(($timelen - 8), 8)
		[int]$hours = $syst.Substring(0, 2)
		[int]$mins = $syst.Substring(3, 2)
		$time = ($hours * 60) + $mins
		Return $time
	}
	
	
	
	function Get-RoomAvailability ($sectiontime, $currenttime)
	{
		$i = 0
		$nextclass = @("Available", "Approaching Class", "Start Time", "End Time", "Index")
		$nextclass[0] = "None"
		$nextclass[1] = "None"
		$nextclass[2] = "0"
		$nextclass[3] = "0"
		$nextclass[4] = "0"
		$times = $sectiontime.Length
		$frames = $sectiontime.Length /2
		For ($i = 0; $i -le ($times - 1); $i++)
		{
			If ($currenttime -ge $sectiontime[$i])
			{
				If ($currenttime -eq $sectiontime[$i])
				{
					If ($i -eq ($times - 2))
					{
						$nextclass[0] = "False"
						$nextclass[1] = "False"
						$nextclass[2] = "0"
						$nextclass[3] = [int]($sectiontime[$i + 1])
						$nextclass[4] = ($i)
						$i = $times
					}
					elseif ($i -eq ($times - 1))
					{
						$nextclass[0] = "True"
						$nextclass[1] = "False"
						$nextclass[2] = "0"
						$nextclass[3] = "0"
						$nextclass[4] = ($i)
						$i = $times
					}
					elseif ($i % 2 -eq 0)
					{
						$nextclass[0] = "False"
						$nextclass[1] = "True"
						$nextclass[2] = [int]($sectiontime[$i + 3])
						$nextclass[3] = [int]($sectiontime[$i + 2])
						$nextclass[4] = ($i)
						$i = $times
					}
					elseif ($i % 2 -eq 1)
					{
						$nextclass[0] = "True"
						$nextclass[1] = "True"
						$nextclass[2] = [int]($sectiontime[$i + 1])
						$nextclass[3] = [int]($sectiontime[$i + 2])
						$nextclass[4] = ($i)
						$i = $times
					}
				}
			}
			elseif ($currenttime -lt $sectiontime[$i])
			{
				If ($i -eq ($times - 2))
				{
					$nextclass[0] = "True"
					$nextclass[1] = "True"
					$nextclass[2] = [int]($sectiontime[$i])
					$nextclass[3] = [int]($sectiontime[$i + 1])
					$nextclass[4] = ($i)
					$i = $times
				}
				elseif ($i -eq ($times - 1))
				{
					$nextclass[0] = "False"
					$nextclass[1] = "False"
					$nextclass[2] = "0"
					$nextclass[3] = [int]($sectiontime[$i])
					$nextclass[4] = ($i)
					$i = $times
				}
				elseif ($i % 2 -eq 0)
				{
					$nextclass[0] = "True"
					$nextclass[1] = "True"
					$nextclass[2] = [int]($sectiontime[$i])
					$nextclass[3] = [int]($sectiontime[$i + 1])
					$nextclass[4] = ($i)
					$i = $times
				}
				elseif ($i % 2 -eq 1)
				{
					$nextclass[0] = "False"
					$nextclass[1] = "True"
					$nextclass[2] = [int]($sectiontime[$i + 1])
					$nextclass[3] = [int]($sectiontime[$i])
					$nextclass[4] = ($i)
					$i = $times
				}
			}
		}
		Return $nextclass
	}
	
	
	
	function Get-TodaysActivities ($loc, $date)
	{
		$sectionmeetings = New-TemporaryFile
		$cookieurl = "https://astra.carthage.edu/Astra/Portal/GuestPortal.aspx"
		$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
		$ckreq = Invoke-WebRequest -Uri $cookieurl -SessionVariable websession
		$cookies = $websession.Cookies.GetCookies($cookieurl)
		$session.Cookies.Add($cookies)
		$baseurl = "https://astra.carthage.edu/Astra/~api/query/vcalendaractivity?fields=ActivityName,StartDate,StartMinute,EndMinute&filter=LocationId=="
		$bi = $baseurl + ('"' + $loc + '"')
		$results = Invoke-WebRequest -URI $bi -WebSession $session
		[char[]]$stuff = $results.Content
		$stuff2 = $results.Content
		$i = 0
		$max = $stuff.Length
		While ($i -le $max)
		{
			If ($stuff[$i] -eq "[" -Or $stuff[$i] -eq "[[")
			{
				$sts = $i
				$i++
			}
			Elseif ($stuff[$i] -eq "]" -Or $stuff[$i] -eq "]]")
			{
				$ste = ($i - $sts) + 1
				$stuff2.Substring($sts, $ste) | Out-File $sectionmeetings -Append
				$i++
			}
			Else { $i++ }
		}
		$sectionslist = New-TemporaryFile
		Select-String -Path $sectionmeetings -Pattern $date -AllMatches | Select -ExpandProperty line > $sectionslist
		$times = New-TemporaryFile
		$times2 = New-TemporaryFile
		$getact = Get-Content -Path $sectionslist
		$events = @()
		Foreach ($line in $getact)
		{
			$i = 0
			$max = $line.Length
			While ($i -le $max)
			{
				If ($line[$i] -eq "[" -And $line[$i + 1] -eq '"')
				{
					$sts = ($i + 2)
					$i++
				}
				Elseif ($line[$i] -eq '"' -And $line[$i + 1] -eq ",")
				{
					$ste = $i - 2
					$actname = $line.Substring($sts, $ste)
					$events += @($actname)
					$events += @($actname)
					$i = $max
				}
				Else { $i++ }
			}
		}
		$eventtemp = New-TemporaryFile
		$events | Out-File $eventtemp
		Select-String -Path $sectionslist -Pattern '\d{2,4}[,]\d{2,4}' -AllMatches | %{ $_.Matches } | %{ $_.Value } > $times
		Select-String -Path $times -Pattern "\d{2,4}" -AllMatches | %{ $_.Matches } | %{ $_.Value } > $times2
		Remove-Item -Path $times -Force
		Remove-Item -Path $sectionslist -Force
		Remove-Item -Path $sectionmeetings -Force
		$todaysstuff = @("Event Names", "Event Times")
		$todaysstuff[0] = $eventtemp
		$todaysstuff[1] = $times2
		Return $todaysstuff
	}
	
	
	
	function Get-LocationID ($bld, $rmn, $locd)
	{
		$name = $bld + $rmn
		$lod = Get-Content $locd
		For ($i = 0; $i -lt $lod.Length; $i++)
		{
			$data = $lod[$i] -split " "
			If ($data[0] -eq $name)
			{
				$res = $data[1]
				$i = $lod.Length
			}
		}
		Return $res
	}
	
#endregion Source: Globals.ps1

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
28sAAB+LCAAAAAAABADtXetzosyz/p4q/wcrn86p2bOjAgJvvbtVKF6jgsYkmi+/8jJ4B4OAyl9/
erioSdSAcXezp868lyiXoeeZp3u6mwb/bZGB4RBzK/esXhI+rCaG/uM28z19+zNxk0z+q5iT0UTv
zYuTOWn0FuRnvTfRi4a5+L5caf/id7v9k/pTMrCS1nZJftzeb1cWWXx/muhDY736Ts/1//8teWzX
t+RjIAX7PUX/+ZbM23PLNskPndiW2Zt/S6p2fz4Z3JFt25gR/Uef53vcgMumRYYlKUG8Teogyo9b
DfqTVnCKtFpNVtZtcjCezIcmnHGbN3TLNOYrf5QgsmoaS2Ja2+BUybaM+0FvTuTJguhUHDg0+y2Z
Zv7F4aEfnVo3huT2ZxGu9OE5+fmE6Nb9xIUTuEz6W5JJpT48icKVM8whMe+t7ZxearIhw/uJPpqT
D0+uDAw9HDzszcEkmtufkiTlJKkpNQvwSSpIJUky6iNJasF/kiytvf15SXrJP0hSid3C91GFHtqU
RtLdqAmfnp7omdBL4ob2UJFyBnyRnAV0kR/5F6CnSbsr+E2Wzjba29sm40tb4ubiU39hb8LJkZ5r
51H4miM935sQD4AAhb9xpOfaaRTOMSS+Tvz5kZ7v7TI2/B7Zfl9v8VAIGXK5hYwj2+/r7T0KUaxl
dBS+zkjP9/Z5nfgFsiHsHN15bDvCmD/fW4QWDYW3DPmcTkSSDR0KiTXGRdhFxw70ehOxxgtYBTyO
4/dBE06ONDobTsoWt8FYvL/9DWIGGa1NPyOs+r31nl9EveJqfX+rw/t/MW/ziBFEzQ22e72cYtNJ
2S7XiavqAoLefMk3orpZ9UWzm/FHLFAcMObQM3rs35NyONpwpJX0EOVnqMdZiElnfexE6E3jz2IR
B4VTDLlMJ87iJvhMyDYMZTSqo5rOqR1/xLBR1Mb6wzBVLtp5vLZ12MTQkaohFkhfk9R9iWw6CtHV
lDaFs9yQW5FQiOtFn0fhIobAtHkMr7uE1Upoxd0hc8LBvO56Wwl4XHkQ2YaMqu3nRjuDtJAVvOjr
h7gdoq4sqYX7CsqtJ6SNkMYEx3wsW3ydoLhdx2vAAXu9T2seD2tNrSDl0DpzP2T0rDMNj1px2khU
GuxLCRXa1QZfT/lMofMdznkrhStPiZuSbWxKyuip2NhkJ4gexaCPWXEchY8YEg+Fo7NAuS4E82Tx
eFxsa9IgjwyjJIr1h0afF9FurSilUfe+ZgnrylAoJ24KyvPTkNCh8b5F9HuZ8OpgXCercdF+rlYV
aVJqZCzTNgO8jq+poWzX8aRj6QKia1ugB2ZWW9YeSOFJRgNcFYVqgTSExM2IULNoCsgbYfZlIc4e
S0QSqg1hUURds0Zqo7QjH44wIzrz/NMwJRVRrlIl0qJEctNHUuYTN6I69a970mJGR+GQIRfpxH4d
c7BAcctmTTRaNIdCDiSXqg3xrmIJbdl+Sa8UT+DAZojpMXooFy2xXLELUzhGKil3zop48+z5Ct4s
ZJE2XzyJQrFIimXA4b5kF3jFcgesv9ScZMRbFKJay2go7BhCJfVlCNib1orzIekqdyJLSraUrdgg
dyOlF4hhNe3OmteCNcI7Xmz3SB10AbDKV2yJA0YUJFWpj4lnAUNebZE2Sz0BRoBCBXRCL9sFpdZg
Sim1vcPrnWxHcYiLwge6QNd23zoJSGWaGbU6JGgwqJFKuyCmuDIpFiskJ1cUSawgbxa0Bp7Z9ASq
NV6buvbaqKDmqGBvyhWRg/+EuxzODe4tXuRxP7QfsDzOhCfL04kS9AaylVGhVLUy6a32Hoe4KFyU
f6NrWKiJd2mtOu6jh3oRjWBOZXvEFdEQZl+UK0RCZUSZwD4VUTNVQ51tFnd83Pw5zjvKKl8R11pF
gdEpuQKgMCiiiqXYmpW44TU1vCbh1dGsYY+6RfJYAsZkgQ2lqpjJbJ1oKFw1/+Z7gwELtqbpSMDQ
5mOeGKmy0kQVEUZvCchjgJKrVER2UlbqBdnOsI7i+hjSVdAbHiombsbKuig5BQxnSnBGEXDoFe0H
UsFl8DJq4XU7aafSLtqpVNGe3wGug7JS6NaHDGxvB73yvyv/FlqhWRY/rp9IXcrhCimhRhk8mkLF
EnMwekCggIEDJRgPjKRZhVlw7pSZUwsxCDVpk3WeG00rBeto2jvaY4MlbEv2w6yolbspNUQh252i
waOMHrjETbXBlYBnU7CQljJkeqzaPpQtFgqx8287BHht2Hq0WFW2m9syasmgz9CbP/5cjuoA/C1X
h6xWFoVSUXlkR+JUxLiNgzgh9IdqabXSrBAjW1aqecBQClBwwUciHg6dlBPikH4hyvo5p+Wq1WE6
ByvKsqTkRq0hxF2hT37Gc7iK1+BZAY8hKd55fHy0hFYBbFR1KJbA3wHtB0Y3xCKMQKgOUwtgw2Me
zZbV4fbxRaHWnueRw7/rLdMA77glo65YsXPAoxzFgWoUC2yYA6OeAjaAlUyvn+z1E1jOEqBQBBSq
RYtzR8GaSqOP0xmJq+Tf/JyHg1mMNtuuaDQLwPlqYP9h7ouVoUjtGlOymyVJ7XZK5HH2SPq1xI2N
Ap+fzv5rzyaLHYNR0WoqK+kKYIc9LKmVFIVO0e5CRFEbMr59pCiYiZs+SXVzSKxWrQ3Y3sK0NOQy
MxT4kDFRiJ1/CxiM7ldkUJEVA2RtyJQDVGaqp+ymjKSHnNN8rJDi6tniyyvkZrF21McNv+dXaP1Y
JM95wBL7PKAroIeDLVVLouA0G8wi62s9NA6P7cGThIu5Cl0viaSUGhwzU/Ye1tt2tfzbXhcswRnM
G2TggOSwVnESsKACa9ZMtmedojKf90WnnkIqi7HsWwAcxoWvWeXFWTxGovssrtW8bUFv7A4Huk5A
r3c5snGfCM1FuEF0jusbZQ3rBAtR1RjWCaECKGwTNzP7MjYcayfzbyET7ibIkMAfSFVIFdZ2iQfm
agWl69QJzpuEZgfAy3Fcz/55Iz2WSwuZ8JhGwnNNnLllGzSLeBYhRKEKPVdzahHNbE+fIF5AYR5S
tfpdVJFk9KhAbKKCbXAICWKJsxHmJ/JvoW/ECmrXVu36Q0GZKzBzDGjlHfi9DbHZI+UNj/VQDjoj
6A0DXrPBz580J2g1LNK11S56dtFbZbBnHRUpBfZVqzQcaYX0ELtQlnlW677U1IIh2xuwx9ziXmRc
LrQfgfZdNf8m7myvtFJSrbwt8GDBuapSaBQtpPRROYuwebj6nWv7/NuUwzOj3mDB04K1kUiH+kA1
vluC1UZFbVZwApPq/wl5mXlRmkPqRY9o1mLbsOXZZ7yGcwzxcAh0ksuOlIGcQ+lcVamoRREpmlKG
S5ro7ZU/yL/5IaAwQl211BCpHQwQCFZJReJgmwSxM542NK+3d5nGAIuplLZYW3GaLQnZ+IU4B/uO
o3BR/i28ekp0HvgmmmlFuyIVxYxE16wyRqou4rOx/THZ8ZBRu1pDqTwCD8qUB966EOJQAAxeSkh6
UWx5xJGdpr3vzb+qkXUeVz1LtIhFLZLzK/Jv4QhXgtZlFFWqSVox3yHltIDPZ3retuD+QpAMmFEm
EwtsQjW3R8BjRQX8oafiMNPSbe/S51fAIKbn6Wx0eVvlkG+hYqHwYf4tnAU9qz64d6r0kCe4trHd
o/Kd1YUQz7WgDVhFmXX99fbVCkkzLRPQhcKDIi8TN6KmH555rucP+fip/FvI4jandZWSYoM3OPK8
wTj5cK+Fx3dSaqUtK+ttSZlDRFmxQhzAJtjSsmyxs7thhneHH2XS3qNBbe9HzLww/xZK/8Coy2ar
4eqcGmmGdm3HkIBXSBmTQUFGAwSeF429KAJUL/IVUlFkZFsLxcu/Bpb0RG8Xtgvzb+FonzjnabAQ
TRDu9d2ASLL5/pNDXZ9x41ExejmnCLFhyovDAAm5aqXuc8h6fgQ/ifbmZdmP3sGM266af3PAf9Pa
SxGFg49mFYMW+lFzFhWWirXuJm4KhObYWORFYxa7LpGuVLH7LdfPOEa2u8dGeq79ovxbNNnCUclb
TWoV7RQDkXg+sAj5CpLuZDTkegqNG5yj2vaF6t/e+caRZQtiHcQ6JPUgaw3ZswjEyyZYJVTXSkQH
25tSfFHPR0bR2hesfwtRAF0wFbaaVxt5z3MmEDvZUr00FFdDQn1gJrQhnxrpufZH69+C+UXVJWHl
nNaA+AHWBiKJEJk9lazs1EDe6vjOIvyfqn8LUWgsbbYIKNB4mkZOozKRVombmoiXjHp4x+ZzIz0r
SqzxX7X+bZcbRJWl4rGB4gD+ojSHuEp7tqk+/Jp14Z0oJ0canw2xZQttAzFttpHXqkWat6wq0qxg
lyazIUXBieeHxGpfpP4t0HjEOYhtyk5DAp+JAy/alsolC2U3ShAbH/EZo7a/ov4ttHzVLUl1SsQg
laEglknhoW4xTxncD46J2Nsn2h+tfwv5zovavNxSHnoyWnFlS5irDX7O7etYfkNl6R+ufwuiKq6Z
uOmR1CCHC0J5yDItkX/hnYANF6wRcWX74/VvYfZwOiWDTsF+2JZEkb0f8lkeh3WPMXq7sP3x+rdw
lITVmuMKYbuyshy0G06KcuFstXDs9oXr3/a5aA5p4/s2Gkh5pSu0G8zoEp24lCF/rP7tlRBBDQMx
0FrKKetM02IW3Il14tdYyz9Q//a2hatmP6UIU/AZHsBzQFo/4+xXis+0KLL9xvq387IFFsDOD+1Z
QVLlkuPfqz+ab/uwt5jtt9S/RWmhHexulZRdtjKVEaEo7O/E/FrP4ZfWv8VrXpxFP6DShKyybXp3
IV5G71X7a/Jvb1u4Jow4PGx07PKcxecz3V8o/3Zd2cL8w8xQeqaO2vvnZT7R6ceyfdnnTzOClkVO
g7GRHWT9I+rHX5d/+6jx3t2LX5iL3vf2hZ8/9SvLr9Xb2fb/z5/S9v/Pn/rtHBvk3U4Nr4NPOYzD
jWX/ZB+3c0fE2U97+1wPh/uht0/2cLg/cXOtUdL9MAtXGiXdv2fvNWQMe7vOTAS9XWkmIvJt672X
xDuo622hbzAJWr4Zfjqn9dSDXfvnUk0Z7WMZ7vfr6dV6249C3o+yeRKEUyh4vZ3E4ULZfl9vMVAI
GHIBGy6U7ff19gYFGOmFbMBHUPhSIz3f2yd1InFzKRsiyOa1N7GBVxnBR6riiYFbBBTeWMtP6kTM
OT31TopjvflbVa+2IV6106F9+5SFxAcofJa9wVxrMBin7z1/6oZPI2NebWcwppXVR9quhoahOZij
WckTsl2oEz5D6GnX0IkD2Rwm/LRgcR9bd7zuFYYHKKxr+AWzizz3topTw4200sfuinf9uxW7EjPv
LRUfRN1nUDjhOVyoE9EYshuaI7JjNMWELRuH+62sZuHNqpu4YVTcSmsHT2hgPBdUFT9m9CXO5OpZ
EI3VgrpQnx3nZLuS10BR+JQu7I2eoOZFVaglbvJIxxPD8Z61DeExejUTrwd3jCraxPLqjGGi9R1b
NoKZwpvKfRYL/Sop46WproKRnstax0QhXE8/7zUEsnnabArhlkzD4bBrrAVVqOZtGS9e1On+eAaP
Ks4Cb7oNxhEmddLBKYthg53ZxE2gBzxOjdu8Jmh5pYNr+fYA825OCOXUmPdm5QgKINuVvIZgpO+a
N/G8l0VU3XDjU0br4Lqr6XjbbHGqMK1YQAETLEEAkIA70Nvj3O3jbbfLasJTwVbx2HANf3SYC1BA
OFNMcY7wWFJk3BhrI5xetlgNi8h/Ws0/5rVsV9CJXW8fs8Fby/idnoqUB9n8POsIz/UGxtWcSaC3
VH3IqkK6QTTMK2YmOFjPYh3XHlQNu/U+7O8WgfPtYh9QcOi6ET6hjjDzLAKO98UGla1+L4/xdrRl
NKyx/n0t7NULHtrXiCgcWMvYOvF27dIE+rQXchy1jB+K0yneNHsMps8Nw6gmOsGbejmLRXes8D5U
gaQbXMbFMT/HbmoCKDhFBIyf9FeAGzI1cS8HwmlLZLFQLTZ43NqWx3hTWDIOllP+XU5fphMoHMYL
n9eJMGpzQ08mCzqJX/iOg12xllWFZhH1cS1XG+NUZcSq4l11iHFt7Gh4W4HlEU9YTXvVG+ot7CmW
RhjOGMxAJ8QyknFhM51hQSsLezlEnM7NgF9PBVLD95PaCHDVGQfhlH/H268nP4lDXBT8kZ7A4eBO
gbxEmqgPYW7zTTzD2zXVfFwhMm7lVRhTdwYo5OmTQTWca05XOHun+6PiAcDgzVSqOO4gFxfXpo5T
MxiVgKjtkEeMifn8NjSxgg1m1B2xiRtYKdwiWMjGGHi4ma3BG3lm1I/ZcAyFI57Dh2zYF0OnLdfF
LssCP5UczGTipnkPmg3jZrBYqMA6cD/pgKYPJgxdJGHuRt2ObxGdg/WTPoKlCdYdamMlp81wqjml
59O72DIuj6Ymzr5MQhzWQt/F23qPw2KO4lTfmIB0gQGd0LM7FPh3lmFn3z7vSWvMvjcYmYobbcrx
+gPMdrUKo25OaoDCYA6jzlSUMi5v5Bks9H0GozudPudGn9f2LahwIFt2MuYpx+0O8If2IFEtKlRh
HSivtdUhCna/k8YbtsE7oGXAt2oOcE6nJ5xfFaYyx2OUC3SCrqfvcKAV8VzwiRVg1K0hjysbqvmj
hSczWCt1zE9B8+scHZPi4Kd5W4feBMILnhngQ7/Xx8E3DaDp1pBXBV0Ghrcoe1KFEbUMFTgqt5F1
nEUbYXcX26454D0JLbCx1SqsFHetNsGZajYbjtSJ5jVQFGLn32CIgU4wiwZoZSdv93E73x9RawZ+
LxZMusaXxtoCp7kXWMOLaxuGqXZCDRL3z94zQRTF40wdr/B2MOKoPaRsypdHdD19mMJKsS2DLSnn
wGKKajPEIWM5oBOjCa+KUglWkkqrP8TpOXuAwisArpV/8311P/+WsVxgZAp0kL5roAZz1wedkFos
6KkCFnLTp48Zgl6r4dxTmd5YK6BVqFngM3adCd4YTTinXAUtUrcyINulWrUu2GAr5KmFEWOj/Xv9
RJxJZ7Ka0CkAe+o5dwi9pedLzrunxeOjMdYV8m9OoJY8N2FNC0xUjVPFShV8gFKuDHxsbEEvXVEL
h+p6olDPAb+XaW9el1nw+FTXnWC3+QwoFKk99FEYwcoiaAVYX/sZZh7MgnoQLyBmjVQh2yAuLks1
Hac3FfCdtll82kIeohAz/wZzGegEI2o615q1gcGre2CwVhKptRwz+oyyBO3yIS4+27SQsagxB8e4
nCsPYdRTsASIrqfUxpZH2BXGsKVeshy86retcGieb77rAT+kiI7vpo6B12w96+BhSg2H670h8FNe
A+AYoIDA3d/l39S01uYqk84Cr2dNVkV5onhPuNBHXP3njc9XZe3f5wCfNQNpwryBavhuY1IdoD6j
5yu1tuoIb2dP1M94EHksatMt9jFGbzIuvo+EszbD4MzzjHPQ04Kor46Ig8Lb/NtrHAIUKlunzeVH
6hqnhk8cfdZeNQOGv77iyUh8z2h224PYsCErfbAtbTr3GoxaolxoedGBBJ432jpaedfbPjN10ALv
ncrg0LeITgXvObwjOcwL8m+wlu1QmAYoINsCFIqbsoXF2l3iJlzDEb3+h4333/fnswUiZKsMKMxk
sPL3+Q6Ns1yW4lCkXkB5XANr85zJeAyIkFPSXmdvr5V/Y8R9/m3PBqQtHZnTdC18rDtSTZ7fGGEv
W6ahpsGvmHCYrjRl3xL464JdBC1ruvwCI361ix+OPD18km+n34NxQf5trxN0BQ50opomDpda7TID
QpynvULhGGz0zCVEQTVY80vUN2reU3vIgsco3BfQFDt9WI/D3o5nZC9oV8u/cdjROK+3bHwp3MB2
mHiguxBzPzRgvS358UJrC7Zhs1Jgy+BZ8ZJQ1OYK5/o7MdJz7Xr5N4f6kPFqz8L8Gy+EXXSKeAse
YJ2jEQisA8oYAwpsH2xufeu//xW/97YijfRcu27+zXl/f+QD2XZve8YpBGxozstrQKHBaWLzDnyj
yrgNUdF8wQU+ZyLCmwSitz+Wf3vb9ihsaI5QeXA30NvWoDjc3cH6WGypBGdLZKdq6pGoKNpIz7Xf
kH87K9sRHPB2rQIKMs0U1O5dgkVmsHM8NOZcb5e2X51/+6g5u0wjS72t9mN/g91CE6LwTQl8hMcU
DyGAlt77IdfQiSOy/ar8W7R24GPS3kzcfWrbNB7lVGFWtHjc1XXfD3GCnPOveer8F+Tf4ssWTjCP
5899C2+6KvhOU4qCtpSXwUHvHOAr1jlcN/92oWx7mlt9JoW3hYcsFqzi0IXe9Cp/Eoe47Yxs18q/
0XbRnewgTx40Hk0z2DWYrCZM8+BJO3e7e7hCFBQuZMi18m+0fa7+LYxARJzhHN4RJAki4vmLagT7
+Vcx4NXaF6t/28dh/IKFdUETpJyi4smy/Wmd+Kvq3w5iv+lWdIR1Teng51J7423SzkdR/8fq3/b5
NzJFLm619TEIuUX7p86v5El/8fq3/ShdwXHxw5M8xoKunvMhz/QWtV2Qf8O/vP7N3TmMptmxcZZM
s2EO03ltIK5kLS/Iv+HfVf+GaT6rQ5/FFu4QxJfr/cs5Lv3Npb+m/u1d83xtz5N+e6fpkt5OtAvy
b/gX1r+9ayfs4dU9hyt5Dfiz9W/HZPt9vUVCQfYfzMh5b65Q/W1l2BY8mqEdHhFnP/hIn+zhcH/A
3k/0cLjf7+0ao6T7vd6uMkrJ7+1Ko/R7i9eDZNAP3pM3Bf9I+qvDQWuejj4oySSPWrSGVVDod2F/
9+70b/Bdrb3rbZ8zZ4SdjLm9jP7PIXs64Vmlzf7U07/QcSXZjrRd3SLW1jsZi3sZC7sxJG5kb+0s
70+Os5Y67+5nXeCl7qqyISzcy/hwsJ7GZcOx5leAHx3d223aifuTfsvueruIDSdlO9Laa/D/MwJ2
ASOXx6JJhFBezwOsbZF6OCb+bZ2q16Kz4RgXPuLb3kudcOUlFpkhor2qLu4U2yP4roW+u72iv/KD
2aLAO9jiw/e1v0H6FBuOccGX7WM2+BXEu5383QaizVkVdWA+5Kz3LIEqTBM3VYvBI8M9eA02g+9T
roW3a4vFeMAeVv357aRlCN9BFJUNwX1netw+FsQbp4OrOZ3WcaUq/luCYVLSDW2Dt4UhowlpRelj
XpMDDws9GQTmsSkDb6pPrF/pdHAVnws+bpewAYf38/dx2Jb+XpuDJ9XyC952FwwWFnlUxqTsBPUh
aG46Mq6MNYK3lQ6nIuRoQUUxt1hksdAtiDyu53lgiwuzsIv1wJbEYQP9/ooLqrtnryVoDs2wrLH7
wHCa8ELre5sbPMLbOr1rp6TVYNqZIpN1BKOoyLi6kaeYK93zu/q3ETd18IZVWFUwaw0YvOiwOwGd
eOuEJ1vABsonnw2pOk9zhDirCZqslHGzBbik1jpc8TlPVDxddrbBNVgEuLcK8hK7q37iBo4wCnAG
YUz/CE3UnwmD79bMBLuFNePgEberCKZ8O20ZwnzIOzbsa7FX/aqgCjqtOm2MtTFOpQyYe6eo1HAl
1xlhljR9OHazIEyroHd6CUZxf0+r1dZ1FiNp6FcHiTBKYLLgFADX9mw6Bb1kd37nARdob2fZABYR
2ABnBGwYclob1bcO4CjRGvlsyaYVnP0pTg/biZusigtO8NIa+gOHAT54xGCb3t1kNbFO7+qVJZgJ
Vin788Tg9kMHLEPqjsHifZd09tYyNDQR2QAWdMTTihOfC5nnDa+xK1p5nbip5zSQWixmHVzc+u8L
yeLwNynDtxcjSkNBaIC+KV690ojWZkwKiorNOz4o/EJ3iZsp2IbCWp7g9HgAMbT42gJFWyeySj8r
ByMtT1h1imv36gJPui2w9CyxpxCn734nObAVVIT9OmG8dBy8nT0wjlj06gyB4fT+qbBkVVqzHj7I
onEIi3ctAlfI8RNYUlboCBuOccHnW8CG0kYzFI9+vYUpYKEgkTKadGu+umvv7NnBelpLw7rAJm6a
gKTS0jW/2lYwC4D0c6c28WU5rAJ0XRGLk2di4nUf2wco7LgAsr1nA8JawIYaYsN1YlTGKZzK5bKe
T+Uc9UuC5wFDZLO6izdrhaUVnETG6oYZUVwZDT8xzqHmH47SERH9X/hOvwhsoPVGPhvSApP1LUOp
NCE83tTlTLhOvIqd9y1E2hGnHcTA3JbBdhg6MFannNfvdnfIXr1/9cB/O/LmoLPrBOAXWgYwMorf
mzDUR2DXwYYe/1XvVw4DZYJb33KOKJXtMq5twLNJPz5lg70g2+m8ZPDboa9kPmsZ6EhPeQ0nampp
20vQSsNc3234BU51x15d9Lxkq7SSP7UDKdY76vZcSNyc9RpglME6sefX8Xji8H2qvFtFsHaVFB03
NuAlpBtPYQVJnHhiz95PeQ3vevObu3NLLKHP4u2gm6XPETVcvFjqq2DXyQq7s1507OjysLcP2VBy
nSm+G+s6WAKNUXHN3T0b6tcnxY1Pz68T9P7phz7k27ZnC5oukSbYVQIM3jJ0XUDlF7TPe8cTFb/m
wuH9rHhsONZ2uCGcSpeyWJRrYHNF3OZ22y95L+incg3vejtoB5Fad7rGW2MB8UFG3P2G9+mbjucY
Ej+6PKwgOt3voT1zcR9XJs4Mo/5yN5/O6V8xO90+sgzAkM/kGkJ+OuLiCdHns2x+eqHN9dorLuzz
IZ/JNYTNw20vk9CuiCrqBL8chQ/tXZQWzsLncg1vezvdvKf5BK3Aqzgtnv3dqnO9XbJOHGh9nEav
5D2/w1z+dv0PLcOhfYvHhiNt/97jC9trLuzyIT4bFE9++qImlfU8s3jfEzdxzzj3HWLnD464ox99
XfNeLgXM8P/uNu/bsXf1iwfa9A7UAw+RD34fEL+yb3vf8vCOi4fs3qYcTvBbW/PqPbT8PjoLW+qg
W8oehjk4ldn9Xh90CyEZr0Ec1kqp9Pn6LGJg4VMfRAdvhNBi764tnkCB9ujsZeSUe0FDw8SNrmA8
ZqdLnO0ZsIW1ISbpPJphYmaH03sUdvk4nrEhLGY2aZDNEYgMkX5maHI4vXnisGh2FQenLYehtdqM
QxN/ZnCmnsWzQxTgMgEKK7O8Tdyg7eqJ1YSB1GDA4+uvwYK5ELV5zwf20qaJs4uZqAlp+hSa90BU
8AQJwtw7FBI36Qb4kBuhymjWqI36eLPqpwO8zRe1jCvr2hAzY4dXUWYFKNS3OkSb9PczA4xVZofC
fl3QOlWb18TswDZDNtC55mjE9JTCc7x9KDIqGtMcoQ/pJgtGZczgaVjhnwWGvMKhw+BO5nnh1DBS
pxApMvsyVkFmwA++Y1Wx00L0YbhpuI9DICfSTP+XXgMGvmIDxPZpUdT6vM/Hg4IGNlPmHWGSb4D5
qndCIobP7e68gnM6sYtweT/34HHR7gG72i4O3Z3j9u2cTuwrEQ58qWFHtjEzdIFvIZ+PPWv3oU74
iB7UYGTvJwJG9YkSjtQ9YsKjWYZX92XGrGri2bIWjv2YX3LWMhzEWa/+0PPkpqiBop562vAICuG6
cNZC+rku7ZSHukchcePjIHvv/1tLdQn+lS/9nrh5u+VfnJvoPXP7M3GThPYvVk1jSUxrtyH8ntR7
C/Ljtt7bTBYTl+SMze3PYm++Ih+e0oD/3/7UDHMhrSyzJ61Wk5X14VltsrFuf3pnJE+dUnCIbgXH
14ze8N1V/kO3/ou948KTlP6UDKyktV3CWffblUUW358m+tBYr74X4fTV91ZvODFytmUZ+rfksSO+
JR+JuZoY+g/2e4r+8y2Zt+eWbZIfOrHh6vNvSdXuzyeDO7JtGzOi/+jzfI8bcNm0yLAkJYi3gdgm
vVbfu1beNk2Qsz0BuJKD8WQ+hK8/bvOGbpnGfHUbDOA9VPkxGcwIjL5t2u+n4/3xRejx9md9MjCN
laFZyfuevkreE3OifUumU8v3QL/vomYMehYAcPszI6a/JVkxwjk+D44POMLp98C625/pNICdYSMc
3+71K/qQAE0zqWiH31vGMjKIPj+DISQjjuFhRR4nK7s3v7e2c5LrDWZ5Y26Ypy96yPBgmvPjnj6i
s30cyf+8PuwN+bHP/i+vC9LcIqbes0h8bbgqu9nUxex+NYTo/M5wsfmdjiJfYE9DoX4NY+Pzq9br
k/kvZ9acXiVQkgYA4emEN2OxqCXZluFP0zUsbSaupaXMyAqRuXhy0NHJKDJwyYjWMyRjFAFfGU9M
hUv6lo6K988VaEUvAC7KLyfWYN5brfTYRDqYVJ6NN6u7K0Y4o0V6Q0WfbyPz1Z/2DMPFn3b+7zIG
8deVP6v8LCN+S/JR1oUD5Y+18rAX6Ho2sq4fFeVLM0SGVfJvYgiT4eMzhA4yOkPY+AzhIjPkqChf
1/L35tYwNkMKeq8/p7778cj5lzAEBk4Cn83HgiIUj1kpMA3iewN/JDsw0ScLexF4DykaqkUxEXWY
g8l8okfXHJ/CwRxE92ciS7RnMBORwNJ8MgKs8uDFEDPKOYYB9nl5m9ws5v+slr0BbFuaZEVMB0gF
HRK4/hCOA0Buk0vTcCZDYv64teA8a7JM3/4s0CslqdokJ3pSM+ZzYz3RR0maA+lZ/yRuutD+p17/
H1n+u/TKir02/516xabEqHp1uYJYsaLPCxQkUqz6BxWEeh4nFKRc/qde/+e/pHrSMJNq/b8TN4mb
v8tJ+USe5LreChvXW2GEiM7EgbdyYUqFycRPqaSvlVL5upbWiyR7Gkgf3+C+DWCZ6H7n68t+sSj2
/eF/w/x9bu5SmQvm7mvN2/sE6BefNli7Pq10aT6KkTqYuOCiX2vq3me+vu7UmYax6Dm9CSxG4I1Z
289NHxPjtsKbC3+tKfzLUn+7XPi91TOtlWT9TVke7yZAjNX2+Iij+05cfDpETwoeJP59yZLglv9d
ZAruYXiDKOjDv5BNcZaRE0OOTic+FZtO0TOI4c14n1FUtL+PT76aDsZkaM/JUKKuVv5vY1Qcj/Lk
oGOsWPE5FTVncfszsE6hbElPuGTAtL+MWy3wIqSL3Zc/z6s4HtPRAcdMGcTjVNRE8e1PKlbyUK6/
kEeN2Pe8/3C+KaqReEOfRrQ77WFxGh+/OC0ebY7K87UjJj02VQ7KjHzB/paMfob5lmSjJPT3YZ0e
i2CeXYqXn49kxf5gft4ak2TfBnLQ1PzAGJKkNjFX1je6Q/f2UpiSur3oE/N74qaw+Z6U7/PJDJdO
/kjKPegWogez5yZ90ZOensDeI7n85OuKSjrsfTllMBn/Odj62erJ31Q4GRSB0sJPOvivf+9srzHp
LC2wjG6Y3ww1Rl0lC9eJlNXfZ4OjRx5UnmREgT5XBAx8mL2D4T/e5jNsff0lwvrgK/cvZ+7eGARC
H3EaVGMpk3lvC6FgKnUkQf/mlIo+sSa9eXBKJsoZq1xvPjcoHY9Xtb5Lra3Gxjq4QPrdBV5jLa1W
ZAFYkFXYW7Bl+3OxGhjmfNK/Ap7/4l2vb6/iz+DvuMbVWfLxFeWe1fs9FzJ79N7xJddKMRqn8Vo6
PeRSPab38bU6i/lvGVMe/J3rX2j31af8v7hFBoZDzC2dq5//Czx1MX7bywAA#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formAstraAssist = New-Object 'System.Windows.Forms.Form'
	$radiobuttonCurrentTime = New-Object 'System.Windows.Forms.RadioButton'
	$radiobuttonAlternateTime = New-Object 'System.Windows.Forms.RadioButton'
	$labelCurrentNextEventName = New-Object 'System.Windows.Forms.Label'
	$classname = New-Object 'System.Windows.Forms.TextBox'
	$labelTime = New-Object 'System.Windows.Forms.Label'
	$labelDate = New-Object 'System.Windows.Forms.Label'
	$altdate = New-Object 'System.Windows.Forms.TextBox'
	$alttime = New-Object 'System.Windows.Forms.TextBox'
	$labelAlternateTime = New-Object 'System.Windows.Forms.Label'
	$classaftertime = New-Object 'System.Windows.Forms.TextBox'
	$classafter = New-Object 'System.Windows.Forms.TextBox'
	$classendtime = New-Object 'System.Windows.Forms.TextBox'
	$roomavailability = New-Object 'System.Windows.Forms.TextBox'
	$labelNextEventStartsAt = New-Object 'System.Windows.Forms.Label'
	$labelCurrentEventEndsAt = New-Object 'System.Windows.Forms.Label'
	$labelEventScheduledAfterC = New-Object 'System.Windows.Forms.Label'
	$labelRoomAvailability = New-Object 'System.Windows.Forms.Label'
	$labelRoomName = New-Object 'System.Windows.Forms.Label'
	$roomname = New-Object 'System.Windows.Forms.TextBox'
	$buttonCheckRoom = New-Object 'System.Windows.Forms.Button'
	$tooltip1 = New-Object 'System.Windows.Forms.ToolTip'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formAstraAssist_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$roomname_TextChanged={
		#TODO: Place custom script here
		$buttonCheckRoom.Enabled = $true
	}
	
	$buttonCheckRoom_Click={
		#TODO: Place custom script here
		$roomavailability.Text = ""
		$classendtime.Text = ""
		$classafter.Text = ""
		$classaftertime.Text = ""
		$classname.Text = ""
		$entry = $roomname.Text -split " "
		$entryarray = @("bld", "rm")
		IF ($entry[1] -eq $null)
		{
			$entrystring = $entry[0].ToString()
			$bld = Select-String -InputObject $entrystring -Pattern "[a-z]{2,4}" -AllMatches | %{ $_.Matches } | %{ $_.Value }
			$rm = Select-String -InputObject $entrystring -Pattern "[0-9]{2,4}" -AllMatches | %{ $_.Matches } | %{ $_.Value }
			$entryarray[0] = $bld
			$entryarray[1] = $rm
		}Else
		{
			$entryarray[0] = $entry[0]
			$entryarray[1] = $entry[1]
		}
		[int]$currenttime = ""
		$realdate = ""
		If ($radiobuttonAlternateTime.Checked -eq $true)
		{
			$date = $altdate.Text
			[System.Collections.ArrayList]$time = $alttime.Text -split ":"
			If ($time[0].Length -lt 2)
			{
				$timeone = $time[0]
				$time[0] = "0" + $timeone
			}
			If ($time[2] -eq $null)
			{
				$subtime = $time[1] -split " "
				If ($subtime[1] -eq $null)
				{
					$time.Add(($subtime.Substring(2, 2)).ToUpper())
					$time[1] = ($subtime.Substring(0,2))
				}
				Else
				{
					$time.Add(($subtime[1]).ToUpper())
					$time[1] = $subtime[0]
				}
			}
			IF ($time[2] -eq "PM" -and $time[0] -lt "12")
			{
				$hours = [int]($time[0]) + 12
			}elseif ($time[2] -eq "PM" -and $time[0] -eq "12")
			{
				$hours = [int]($time[0])
			}else { $hours = [int]($time[0]) }
			$minutes = [int]($time[1])
			$currenttime = ($hours * 60) + $minutes
			[System.Collections.ArrayList]$datetest = $date -split ($date.Substring(4,1))
			If ($datetest[1].Length -lt 2)
			{
				$datetest[1] = "0" + $datetest[1]
			}elseif ($datetest[2].Length -lt 2)
			{
				$datetest[2] = "0" + $datetest[2]	
			}
			$date = $datetest[0] + "-" + $datetest[1] + "-" + $datetest[2]
			$realdate = $date + "T00:00:00"
		}
		Else
		{
			$currenttime = Get-CurrentTime
			$currentdate = Get-Date -Format FileDate
			$year = $currentdate.Substring(0, 4)
			$month = $currentdate.Substring(4, 2)
			$day = $currentdate.Substring(6, 2)
			$realdate = $year + "-" + $month + "-" + $day + "T00:00:00"
		}
		$datapath = "C:\Program Files (x86)\Carthage College\Astra Assist\Data.txt"
		$locid = Get-LocationID $entryarray[0] $entryarray[1] $datapath
		$events = Get-TodaysActivities $locid $realdate
		$acts = Get-Content $events[1]
		$acts = $acts | ForEach-Object { [int] $_ } | Sort-Object
		$actnames = Get-Content $events[0]
		Remove-Item $events[0] -Force
		Remove-Item $events[1] -Force
		$results = Get-RoomAvailability $acts $currenttime
		$actindex = ([math]::Round($results[4]))
		$starttime = Convert-Minutes $results[2]
		$endtime = Convert-Minutes $results[3]
		If ($results[0] -eq "True")
		{
			$roomavailability.Text = "Room is Available"
			IF ($results[1] -eq "True")
			{
				$classafter.Text = "There is a Scheduled Class coming up"
				$classaftertime.Text = $starttime
				$classname.Text = $actnames[$actindex]
				$labelCurrentNextEventName.Text = "Next Event Name:"
			}
			Else
			{
				$classafter.Text = "Nothing Scheduled for Remainder of Day"	
			}
		}
		elseif ($results[0] -eq "False")
		{
			$roomavailability.Text = "Room is Unavailable"
			IF ($results[1] -eq "True")
			{
				$classafter.Text = "There is a Scheduled Class after Current"
				$classendtime.Text = $endtime
				$classaftertime.Text = $starttime
				$classname.Text = $actnames[$actindex]
				$labelCurrentNextEventName.Text = "Current Event Name:"
			}
			Else
			{
				$classendtime.Text = $endtime
				$classafter.Text = "Nothing Scheduled after Current Class"
				$classname.Text = $actnames[$actindex]
				$labelCurrentNextEventName.Text = "Current Event Name:"
			}
		}
		Else
		{
			$roomavailability.Text = "Room is Available"
			$classafter.Text = "Nothing Scheduled for Remainder of Day"
		}
	}
	
	
	
	
	
	
	
	
	
	$radiobuttonCurrentTime_CheckedChanged={
		#TODO: Place custom script here
		IF ($radiobuttonCurrentTime.Checked -eq $false)
		{
			$altdate.Enabled = $true
			$alttime.Enabled = $true
		}
		elseif ($radiobuttonCurrentTime.Checked -eq $true)
		{
			$altdate.Enabled = $false
			$alttime.Enabled = $false
		}
	}
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formAstraAssist.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_radiobuttonCurrentTime = $radiobuttonCurrentTime.Checked
		$script:MainForm_radiobuttonAlternateTime = $radiobuttonAlternateTime.Checked
		$script:MainForm_classname = $classname.Text
		$script:MainForm_altdate = $altdate.Text
		$script:MainForm_alttime = $alttime.Text
		$script:MainForm_classaftertime = $classaftertime.Text
		$script:MainForm_classafter = $classafter.Text
		$script:MainForm_classendtime = $classendtime.Text
		$script:MainForm_roomavailability = $roomavailability.Text
		$script:MainForm_roomname = $roomname.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$radiobuttonCurrentTime.remove_CheckedChanged($radiobuttonCurrentTime_CheckedChanged)
			$roomname.remove_TextChanged($roomname_TextChanged)
			$buttonCheckRoom.remove_Click($buttonCheckRoom_Click)
			$formAstraAssist.remove_Load($formAstraAssist_Load)
			$formAstraAssist.remove_Load($Form_StateCorrection_Load)
			$formAstraAssist.remove_Closing($Form_StoreValues_Closing)
			$formAstraAssist.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formAstraAssist.SuspendLayout()
	#
	# formAstraAssist
	#
	$formAstraAssist.Controls.Add($radiobuttonCurrentTime)
	$formAstraAssist.Controls.Add($radiobuttonAlternateTime)
	$formAstraAssist.Controls.Add($labelCurrentNextEventName)
	$formAstraAssist.Controls.Add($classname)
	$formAstraAssist.Controls.Add($labelTime)
	$formAstraAssist.Controls.Add($labelDate)
	$formAstraAssist.Controls.Add($altdate)
	$formAstraAssist.Controls.Add($alttime)
	$formAstraAssist.Controls.Add($labelAlternateTime)
	$formAstraAssist.Controls.Add($classaftertime)
	$formAstraAssist.Controls.Add($classafter)
	$formAstraAssist.Controls.Add($classendtime)
	$formAstraAssist.Controls.Add($roomavailability)
	$formAstraAssist.Controls.Add($labelNextEventStartsAt)
	$formAstraAssist.Controls.Add($labelCurrentEventEndsAt)
	$formAstraAssist.Controls.Add($labelEventScheduledAfterC)
	$formAstraAssist.Controls.Add($labelRoomAvailability)
	$formAstraAssist.Controls.Add($labelRoomName)
	$formAstraAssist.Controls.Add($roomname)
	$formAstraAssist.Controls.Add($buttonCheckRoom)
	$formAstraAssist.AutoScaleDimensions = '6, 13'
	$formAstraAssist.AutoScaleMode = 'Font'
	$formAstraAssist.ClientSize = '521, 300'
	$formAstraAssist.FormBorderStyle = 'FixedSingle'
	#region Binary Data
	$formAstraAssist.Icon = [System.Convert]::FromBase64String('
AAABAAQAQEAAAAEAGAAoMgAARgAAADAwAAABACAAqCUAAG4yAAAgIAAAAQAgAKgQAAAWWAAAEBAA
AAEAIABoBAAAvmgAACgAAABAAAAAgAAAAAEAGAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD/////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////
////////////////////////////////////////////////////////////////////////////
///+/v/////////////////////+/v/////////////////+//7/////////////////////////
//////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAD/////////////////////////////////////////////////////////////
///////////////////////////////////+///////////8/f3z+/z+////////////////////
///9/f78/P7//v////////////////////////////////////////////////////8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////
///////////////////////////////////////////////////9/f/////bx+3c2fT////+/P//
//aZq9nIzfb////+/v7////+//7u7+389fz////+/v/9/f/+/v//////////////////////////
//////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////
///////////////////////////////////////////////////////////////////////////+
/v/////x9Pxsb9rY2fb////8/P////5+Z+VbSeH////+/v/+/v/////I1d+Ck+a5t+316fT////9
/f7+/v////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////////
///////////////////////////8/f////6NoOggM+Ln5PX////+///69fhnUd0HFuC/wun///39
/P/+/v////+nwe0SGexXOenP0fj+//z9/f////////////////////////////////////////8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////
///////////////////////////////////////////////////7+/7////Mze4fG+s5K+ri5fT/
///////s8/hIU94ND+JTZNT2+fH////+/v79/v7///9yd+YDAPESI+BwieT++f3////+/v//////
//////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAD////////////////////////////////////////////////////////////////////////9
/f/////w7/dLQfEAB+w2Sd3n6vj////////s5fg9ON4qG+ETJN7M0PX////9/f/9/f/////R0/IW
GuoxGOgWFNx6i+X///3+/f////////////////////////////////8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////
///////////////////+///8/v/////t7/hFTfAcC+ooG99MUNb79+/+///////G1+YSLt8wId8H
EOZWdef///7+/v/9/v/////i7PchMeshFuZJJOAiGN2trur////9/f7/////////////////////
//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////
///////////////////////////////////////////+/f78+/7////r6fpLUeEWD+c/J98JEeN8
geP///r8+v////6qm9kVGeA8JN8mF+YrLeLg1vD////9/f7////29vlCWd0AF+BIJeAmGeBjVeH7
9Pj////+/v////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD////////////////////////////////////////////////////9/f/+/v///v/8
//66r+gmQd8BF+BAJN9KIt8TDuq1sOv////7+/7///91h+UHFt9HIuEjIt8AGOKvser////8/P7/
///6+flmW98FFeFHJeASGuE7Otzc4/P////9/f7///////////////////////8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////
///////8/P79/f7//v/////i1fFldeYOK94eGuA6IuFHJN0nEeotQuXw7fX////+/v////9TaeMH
F+BCIuA5JN8EAPOMhe3////8+/7////y+fk0Wt8AFeFIJOAnHuEOLN3G0PT////8/P7/////////
//////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////
/////////////////////////////v/+/f/////8+P3Q2PJde+ccLeITE905HeFFIeBDIOA9I+AA
AfN/ku////78+//////jzuwoI+QgEuxHI95HI98KB/BcSt797/b+///////z9/k8Wt0AF+BGI+A/
H+EGJt21yfT////8/P7///////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD////////////////////////////////9/v7+/v/////K1fJhb+UMF+gH
Dug5F+dHJN9DIeA+H+FHJN4WF+Q0L+Xy6/X////8+/7////CvOsCI9wfIOBGIOBEI98cF+ItOuft
7fP////////e7PgkNugYFeVGJN86HuEGJ922yvT////8/P7///////////////////////8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////////////////+
/v/+/f////yrrvAIJOQVCeo0HOQ+I99DIt8+IOA9IOBII94iHOMEDu24vOz////9/f/9/P////+F
hOwFAvE/I99AIOBFI98aFuUeI/He4fL////////X1vITFu00FulKJN4cHOEYMd3X1vT////9/f7/
//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
///////////////////////9/f7////k6/VwWeMAB/IeG+NHI+BEIt9BIOA+IOE/H+FGI98/HeQJ
AvKOkvL////9/f/+/f/////x6vZNQt0cC+1GI98/IOBEIt8yGuUkFfHY0PL///////6Yj+cVD+U5
JN5GIeAjGuEtOd3a4PT////9/f7///////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////////9/f7////k7fdRVt4PDuQyH+RDI95A
IOA+IOBBH+FHIOBHJd4fH98GFOV4g9j9//T//v/+/v/9/f/////L1PIQIeo6HOJCIt9AIOBEIt8z
GeUkFfHX0vL///////1qeOwZBfBJJd1BIuEpGOBgRd7u7PX////+/f7/////////////////////
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////////+/v//
///07vVVVt8RE+A/Jd9GId8+H+E/IN9FIt88Jd0mIOEVC+kpJdyVqO3///77+v7////////+/v//
//2Nd+YRD+Y9IuBBIOBAIOBDIt84GuUlE/HW0PL////+//1wWuwWB/BGJd1FIuEJFt5zger////8
/P7///////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD////////////+//7//v/4/+xyY9oQEOE/JeBDIOA9H+FFId9EI983GuQGAPYXGeVkVebL
u+3////+/f///v/////////////6/vo3P+sjDO1IJd0/H+E/IOBGI98XFuYfH/Ld3fP////+//1r
be0YB+9JJtxDIeEjGd52k+r////9/P7///////////////////////////8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////9/f////+SsecIDOo/IONDId8+IOBG
JN4xH+AUBvQVIeFsZt7Hs+z6/fr////9/f7////////////9/f7////Cs+wVFeZCIOA/IOBAIOA/
IOBGIuAJG98vQN3m6PT///////5/hucWA/FBI+BGIeAOGN53kOr////8/P7/////////////////
//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////+/v//
///t8vclNecvFeZGJN5AH+FIJN8kDukXFOllb9vM0+P4//D//v/+//79/v7////////////+//7/
/f/7/+9zZ9wPCutGJN4/IOBAIOA/IOBFJN8KBexzWeb///z8/f/////MxOwTFu4xGOhKJN8IGN5y
kur////9/P7///////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAD////////9/f////+Ki+oADug0IeJGIOA7I98fEOYvMe/Cren///b+/vz+/v/9
/f/+///////////////////9/f7////V1+8ZL9kzHuBDIeBAIOBAIOA/IOBJI98JBPF+ku3////7
+/7//////PtbY+IAD+VOJ98PFt5veej////+/f////////////////////////////8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////+/v/////48PYuPuMUEOlOJN43IeEK
FN9QaeHx7/n////+/f/9/P7+/v7////////////////////////+/v////+Qi+sdFt9BIuFBIOBA
IOA/IOBDIOA0IOEfINvAs+n////9/f7+/v/////l6fYqLPEoDuxFIt5mS93z5fP////+/f7/////
//////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////9
/P7////AsO0RCu87It85JOENFt+Ob+H6+/r+/v/9/f/////////////////////////////////+
/v/////j5/koMN40HOBEIeA/IOBAIOA/IOBGIeAYGt88P+T48vv//////v/////9/f////+2qOQd
H+gAB+wyNuDk4PT////9/f7///////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD////8/f////56gOcDB+1BJOIPF9+OfOH/9/r+///9/f7/////////
///////////////////////////8/P////98g+YPGN9GIuA/IOBAIOBAIOBDIOA5IuAAGeB/jNf/
//7+/v/////////////9/f////jA1t4uOvQRA+u/qev////9/f////////////////////////8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/v/////09vU7Q+kfFuIAF92A
beH/+Pn9///+/v/////////////////////////////////////9/f/////d3PYfNOIVHOBHIeA/
IOBAIOBAIOBEIuAqG+AqOuDg5en////+/f/////////////////9/v/////o6vVsat9tetz+/vv/
//////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAD+/v/////s8fY3OPALAfFCXeH18/r////9/f7/////////////////////////////////////
///9/P////9/k+gABetBIuJBIOBAIOBAIOA/IOBIIuEWFd2Rnuv////8/P7/////////////////
///////9/f7//v79///Y7uP5+/n///////////////////////////8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/f/////n6PUzKPAUCe/Lxuz////8/P7/////////////
///////////////////////////+/v/////w8fc4OOkYFeZGJN4/IOBAIOA/IOBHIuEiGeBEUODp
9fn////+/v/////////////////////////////+/v/+/v//////////////////////////////
//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9/f/////T5fYOGOuL
g+3///z9/f/////////////////////////////////////////////9/f/////X0PITDOwyGOlF
It4/IOBAIOBDIuApHt4kKd27zdj////+/v/////////////////////////////////////////+
/v7///////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD9/f/////U3PpQRNzn5Pn////+/v//////////////////////////////////////
///////+/f////+OhecED+c+JN5BH+FAIOBBIOBCIeIOD+utmOf///78/P//////////////////
//////////////////////////////////////////////////////////////8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/v/////W5vWcm9r78/3////+/v//////////
///////////////////////////////+/////v/7//hNVOoaBvFJJd0+H+E/H+FDJt0SB+tZVu3/
//3+/f/+////////////////////////////////////////////////////////////////////
//////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////v
+fTp9+v///////7////////////////////////////////////////////+/v7////l4+EpOtwY
EexHI94+H+FFIt4wGeYAIubRze3////9/f7/////////////////////////////////////////
//////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////////////
///////////9/f7////DyfARFu03IN9CIOBAIOBCI+AKD+d5aOb///v+/v//////////////////
//////////////////////////////////////////////////////////////////////8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////+/v7/////////////
///////////////////////////////////////9/P7///+4ve0UDfNDH+FAIeBDIt8tG+MfGenL
0O/////8/P7/////////////////////////////////////////////////////////////////
//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
///////////////////////////////////////////////////////////////////9/P7///+Y
rO4JCPNCIeA/IeBJIuAMGd9sdeT///3+/////v//////////////////////////////////////
//////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////
///////////////////8/P7///+Jpe4DBfNEIeBBIeA9IeEWGt6jo+j////9/f7/////////////
////////////////////////////////////////////////////////////////////////////
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////
///////////////////////////////////////////////8/P7///+Npu4FBfNDIeBGIeAgHeAs
L9/p3PX////+/v//////////////////////////////////////////////////////////////
//////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD////////////////////////////////////////////////////////////////////8
/P7///+IpO4DBfNDIeBHIuAlGN9fZuT///7/////////////////////////////////////////
//////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////
///////////////////////////9/P7///+eru4NCfJFIOA9JOAkEuGikdT///v+/v//////////
////////////////////////////////////////////////////////////////////////////
//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////
///////////////////////////////////////////////////////9/f7///+5v+4QDvNAH+E5
IuAHGt+6xOv////9/P//////////////////////////////////////////////////////////
//////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAD/////////////////////////////////////////////////////////////
///////9/f7////Jye0XGeoeId89HeEUMt3W2/b////9/f//////////////////////////////
//////////////////////////////////////////////////////////////////8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////
///////////////////////////////////+/v/////79flHROUaD+s5Ht8lPN7l5PX////9/f//
////////////////////////////////////////////////////////////////////////////
//////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////
///////////////////////////////////////////////////////////////////+/f////5Q
ae0cB/E8Hd43R97q7vb////9/v//////////////////////////////////////////////////
//////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////////
///////////////////9/f////+jjecXEuUyG994Sd767/b////+/v//////////////////////
//////////////////////////////////////////////////////////////////////////8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////
///////////////////////////////////////////////+/v/////e4fQhIe4YDOpcTNv07vb/
///+/v//////////////////////////////////////////////////////////////////////
//////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAD////////////////////////////////////////////////////////////////////////+
/v/////5+fhST+cACOY8TN3g7vb////9/v//////////////////////////////////////////
//////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////
///////////////////////////////8/P////+eo+wABOw2Qt3m5/b////9/f//////////////
////////////////////////////////////////////////////////////////////////////
//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////
///////////////////////////////////////////////////////////9/f7////b0O8jIuAU
I+fb2vX////9/f//////////////////////////////////////////////////////////////
//////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD/////////////////////////////////////////////////////////////////
///////////////+/v////uCdukEAPDGvPL////8/P//////////////////////////////////
//////////////////////////////////////////////////////////////8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////
///////////////////////////////////////////+/v/////YyO0uHt2IgeL///7+/v//////
////////////////////////////////////////////////////////////////////////////
//////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////
///////////////////////////////////////////////////////////////////////////8
/P////+Gies6T9////7/////////////////////////////////////////////////////////
//////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////////////
///////////////////////////9/v/////g5/dNXuHl4/n////+/v//////////////////////
//////////////////////////////////////////////////////////////////////8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////
///////////////////////////////////////////////////////////8/P7///+koOarn+T/
///9/f7/////////////////////////////////////////////////////////////////////
//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
////////////////////////////////////////////////////////////////////////////
///////////////////28f6+vN3u+u3////+//7/////////////////////////////////////
//////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////
///////////////////////////////////////////////////7/v/7/v//////////////////
////////////////////////////////////////////////////////////////////////////
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////
////////////////////////////////////////////////////////////////////////////
/v///v//////////////////////////////////////////////////////////////////////
//////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAD/////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAA
AAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAA
AAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAA
AH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAA
f/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB/
/AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8
AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wA
AAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAA
AAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAf/wAAAAAAAB//AAAAAAAAH/8AAAA
AAAAf/wAAAAAAAB//AAAAAAAAH/8AAAAAAAAfygAAAAwAAAAYAAAAAEAIAAAAAAAACQAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP//////
///5////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAA
AAAAAP///wYAAAAA////gP/////////5////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////P/////////DAAAA
AP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////
gP/////////5////////////////////////////////////////////////////////////////
//////////////////7//////////////v7///7+////////////////////////////////////
/////////////////////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAA
AAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////////////////
/////////////////////////////////////////////v/////////////////////+////////
///////////+/////P3+///+/////////////////////////////////////////////P//////
///DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////
//////////////////////////////////////////////////////////////7+/////f//+vb8
//z8/v//////7PT2//H6+////////////////////v7///////39///9/f//////////////////
/////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYA
AAAA////gP/////////5////////////////////////////////////////////////////////
/////////v3////////m4/b/tK7n//j5/v//////wL/q/4mC5v/+/v///////////f/N1Ob/zs7z
///++v///////fz///7//////////////////////////////P/////////DAAAAAP///wQAAAAA
AAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////////
////////////////////////////////////+/v//////v94h+j/e4Ho////////////t6ft/xsY
3P/R1fD////////9///l8PP/V2np/2BM6//g4fj////+//39////////////////////////////
/P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5
///////////////////////////////////////////////////////////7+////////8PC9P8L
C+n/iovu/////v//////oaLr/wcK3P9uetz////7//n5/v//////x8r0/xIS6/8bJeH/prPs////
///8/P///////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAA
AP///wYAAAAA////gP/////////5////////////////////////////////////////////////
/v7///r8////////2Nv5/zow8P8JCuD/mqPj//////////3/gIvm/xYN3v8iMeX/0t34///////6
+v/////7/0hT7f8fCOX/LCTc/7zB8P///////f3+/////////////////P/////////DAAAAAP//
/wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////
//////////////////7+///7/P7//Pz////////W2fX/Mzfn/yQR5P8jIt//vr/q///////28/X/
Vlzb/yYY4f8WEuP/hozo/////f/5+v/////+/2F05v8VGOD/Nhfg/1pR4f/9+fr////////+////
/////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP//
///////5/////////////////////////////////P3+//79////////9/r8/6Cl6v8ZMN//JBre
/0Md4P81Nef/7Or2///////n6/n/LUPf/zMb4P8YFeH/TFbo//v6+//8+//////+/3Z95P8SFN//
MSDh/ygy3f/f4vX///////3+/v///////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAA
AAAAAAAAAP///wYAAAAA////gP/////////5//////////////////////39///9/f////////f8
+/+vvPH/UFjj/xQa3/8yGuH/Tine/xMH6/9zhO7////9///////Px/H/Fh7l/z0i4P8vF+X/Libs
/+rf9P/////////+/1t94/8JFN7/RyHh/xEp3v/D0/b///////39/v///////////P/////////D
AAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////
/////Pz+///+///6/f3/q7Xv/z9L6P8QF+b/LBLh/0Ig4P9KJd//Lhvf/yIj5//i4ff/////////
//+amuj/Ag/h/0ck4f89H+D/Exjk/8fH8P/////////9/1Bk6v8WEeL/SiLg/xMn3v+/0vb/////
//39/v///////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA
////gP/////////5///////////9/f7///////Dp+f9ndO7/CQ/k/ywR5P8/IeD/RCPh/0Yk4P9C
IOL/BQjs/6Kn8P////7/+/z////+/P9hX+z/Fwrn/0kn3v8+It//Dg3r/7Cy8///////8u/3/zg4
6/8zFOX/Nh/f/xkw3//Z3Pb///////39/v///////////P/////////DAAAAAP///wQAAAAAAAAA
AAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5//////v7////////1tzz/z444/8OBuj/
QSPf/0Yk3/9EIuD/SiXf/zci3/8PCeL/gYXq/////v/7+////////+Pn9f8tK+T/OBfk/0Qj3/9E
I+D/Hgjr/6qi8///////w8bz/yMa5/9BIt//Mxrh/0E33v/n6Pb///////7+/v///////////P//
///////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5/f3/
///////i3/P/NTvf/yMU4P9JJuD/QiLf/0cl3/82IOH/HxDk/x8b3/+Knev//v/4//79///8/P//
/////6ih7v8WEuX/RCLf/0Ag4P9EJOD/Hwfs/6qi8///////ubX1/x4N7v9KJeD/JBXf/11i5f//
/P3//v///////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP//
/wYAAAAA////gP/////+/v75/////+/48P9JRd7/IxLh/0gm4P9EJN7/Ph7j/yIM5v8WEOv/WlTn
/8e78f////7//fz///79///8/f/////9/1td7P8nDOX/RiXf/0Eg4f89I9//BxDn/6+x8v//////
uLv0/x8R6/9JJN//KRTe/2J66P///////v3+/////////////////P/////////DAAAAAP///wQA
AAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////7/P/5/////3mN6/8XCub/TCbg/0ck
3/8rEuP/Ghfm/15q4f/Fwuf//PX7///////9/f///v////38/v////7/2M/s/ycg5f89HuD/QCHg
/0Uj4P8yHOL/HB/h/9PQ8v//////2tvz/ygi7P9AG+X/IRbd/1l46P///////v3/////////////
/////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP39////
///52tz1/x0n6P83GuL/Ribf/yAR4/9BOO7/xb/r//3/9P////7//f3///39/v////////////v7
//////3/gYvi/xoQ3/9HJOH/PyDg/0Yl3/8wEuT/ODjt/+3u+f/+/v/////9/2126f8XEOX/MBzd
/1lp5v///v7///7//////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAA
AAAAAP///wYAAAAA////gPv8//////75i4rt/w8L5P9IJuH/GBHe/2Ny5f/z9fv///////z7///7
+/////7//////////////v7////////p6fr/Pzzi/zQZ3/9FI+D/PyDg/0gk4P8fEd//b23l////
/P/8/P///////+3w+P86Nez/HALn/1xI3f/y6/b///////7+/v///////////P/////////DAAAA
AP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA/f3/gP/////39fn5RkTs/ysS5f8fG93/
h3nk///5+//+/////Pz//////////////////////////////f3///////+Nl+v/HBHd/0gj4f8+
IOD/QiHg/z8h4f8MGtv/sbTt///////7/P7//f3////////U0en/Kjvo/w4M6v/d0PP///////39
/v///////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP7+/wYAAAAA+vr/
gP/////P1fT5IiXm/wkQ4P+CeOT///37//v9///+/f/////////////////////////////+/v//
/////+fo+f8lN+L/Kxrg/0Yi4P89H+D/RyPg/ykW4P9CU97/9fjy///+///+/v7///////39////
//3/6u33/2Zk5v+WmeP///////39/////////////P/////////DAAAAAP///wQAAAAAAAAAAAAA
AAAAAAAAAAAAAP7+/wYAAAAA+vr/gP/////IyvT5CgPw/0dW5v/9/Pr//v7///39////////////
///////////////////////8/P///////4ya7f8NDOb/RiTg/z8f4P9AIOD/RSDh/yAa3/+yvfH/
//////z8/v/////////////////9/f////7///v+/P/j8e3///7+/////////////////P//////
///DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP79/wYAAAAA+vj/gP////+utvT5FxHt/9LK
8///////+/v+//////////////////////////////////7+///8/f/////7/0tH7f8kD+X/SCXe
/z4f4P9FJeD/HhLe/2Z22//+//z///7//////////////////////////////f7///7+////////
/////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP39/wYA
AAAA+vr/gP////+fpvD5fnfn///////8/P////////////////////////////////////////38
////////2NP1/yIi5/83GuH/QiHg/0Yl3/8uFOT/Qz7m/+7s8P///////v7/////////////////
///////////////////////+/v7//////////////////////P/////////DAAAAAP///wQAAAAA
AAAAAAAAAAAAAAAAAAAAAP7+/wYAAAAA/v3/gP/////J1ev50s/q///////8/f7/////////////
//////////////////////////v7//////3/oarp/xML7P9GI9//QSHg/z4g4P8SE+j/vbz1////
///6+///////////////////////////////////////////////////////////////////////
/P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////5/vf5
/P/6//////////////////////////////////////////////////z9//////r/cnzj/xUN5P9G
I+D/RyTg/xsO5P9cZOj////7//v8////////////////////////////////////////////////
/////////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAA
AP///wYAAAAA////gP///////v/5//7/////////////////////////////////////////////
/v7///78//////v/XF/y/ygM5P9JJ97/Oh/g/x4b5v/MyfH///////39/v//////////////////
/////////////////////////////////////////////////////////P/////////DAAAAAP//
/wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5/v/+////////////////
/////////////////////////////v7////+///0+/r/QlHw/ygN5f9QKd//IhTf/1lm5P////7/
/v7/////////////////////////////////////////////////////////////////////////
/////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP//
///////5/////////////////////////////////////////////////v7////+///x+fr/OUzx
/yoN5f9KKOD/FRPe/6Ge6////////P3+////////////////////////////////////////////
/////////////////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAA
AAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////////////////////
/////////v7////+///x+fr/OUzx/ywP5f9DIt//LSze/93c9////////f3/////////////////
/////////////////////////////////////////////////////////////////P/////////D
AAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////
/////////////////////////////////////v7////9///4/Pr/TVbx/zEQ5v8xGeD/V07b//f1
8////////v7/////////////////////////////////////////////////////////////////
/////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA
////gP/////////5/////////////////////////////////////////////////v7///39////
//r/YWTu/yAR5P8kFt7/Ynnn/////v/8+////v//////////////////////////////////////
/////////////////////////////////////////////P/////////DAAAAAP///wQAAAAAAAAA
AAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////////////
//////////////////////v7//////7/lZbt/xYP5/8jFt7/fpDp///////7+///////////////
/////////////////////////////////////////////////////////////////////////P//
///////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////
//////////////////////////////////////////////////v7////////tb30/yEU6/8tFdz/
nJ7p///////7+///////////////////////////////////////////////////////////////
/////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP//
/wYAAAAA////gP/////////5////////////////////////////////////////////////////
//39////////7+j2/zo36f8jCuH/vKHo///////8+///////////////////////////////////
/////////////////////////////////////////////////////P/////////DAAAAAP///wQA
AAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////
///////////////////////////////////8/P/////9/25v7v8AAeP/lqPo///////7/P//////
////////////////////////////////////////////////////////////////////////////
/////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP//////
///5///////////////////////////////////////////////////////////8/P///////7m4
8f8ABOP/ipTp///////7+///////////////////////////////////////////////////////
/////////////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAA
AAAAAP///wYAAAAA////gP/////////5////////////////////////////////////////////
///////////////+/v7///////jy9v8wLOX/ZGTx/////f/6+///////////////////////////
/////////////////////////////////////////////////////////////P/////////DAAAA
AP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////
/////////////////////////////////////////////////f3///////+ej+z/RTnh//Py+f//
/////v7/////////////////////////////////////////////////////////////////////
/////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////
gP/////////5////////////////////////////////////////////////////////////////
/v7////////z8vz/UWDh/8nP9////////f3/////////////////////////////////////////
/////////////////////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAA
AAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////////////////
//////////////////////////////////z8////////rrXu/6ej6f///////v7+////////////
/////////////////////////////////////////////////////////////////////P//////
///DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////
//////////////////////////////////////////////////////////////7+////////+fX+
/8K+5P/w9/P///////7//v//////////////////////////////////////////////////////
/////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYA
AAAA////gP/////////5////////////////////////////////////////////////////////
//////////////////////////7///3//v/8/v3/////////////////////////////////////
/////////////////////////////////////////////////P/////////DAAAAAP///wQAAAAA
AAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5////////////////////////////
/////////////////////////////////////////////////////v7/////////////////////
////////////////////////////////////////////////////////////////////////////
/P/////////DAAAAAP///wQAAAAAAAAAAAAAAAAAAAAAAAAAAP///wYAAAAA////gP/////////5
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////P/////////DAAAAAP///wQAAAAAAAAAAAAAAADwAAAAAB8A
APAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA
8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADw
AAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAA
AAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAA
AAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAA
AB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAADwAAAAAB8AAPAAAAAA
HwAA8AAAAAAfAADwAAAAAB8AAPAAAAAAHwAA8AAAAAAfAAAoAAAAIAAAAEAAAAABACAAAAAAAAAQ
AAAAAAAAAAAAAAAAAAAAAAAA////AQAAAAD///8O////8f/////////+////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////6/////////38AAAAA////BQAAAAD///8BAAAAAP///w7////x//////////7/
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////r/////////fwAAAAD///8FAAAAAP///wEAAAAA////
Dv////H//////////v///////////////////////////////////////////v7///7+////////
/v7/////////////////////////////////////////////////+v////////9/AAAAAP///wUA
AAAA////AQAAAAD///8O////8f/////////+////////////////////////////////////////
///+/v///////////////////v///////////////f3///7+///////////////////////6////
/////38AAAAA////BQAAAAD///8BAAAAAP///w7////x//////////7/////////////////////
//////////////////////Tw+f/28/z/+vz7/9re8////v///v7+//Ly+P/+/v////////7+////
//////////////r/////////fwAAAAD///8FAAAAAP///wEAAAAA////Dv////H//////////v//
//////////////////////////////z8////////i5Hp/93d+P///Pz/XFTg/93f9///////usft
/4F87v/t7vv///////7+////////////+v////////9/AAAAAP///wUAAAAA////AQAAAAD///8O
////8f/////////+//////////////////////7+///7+////////7Kx9v8kJ+X/7/D6//j5/P8j
Jt3/gozn//////////3/S0zt/ywt4//c4Pb///////39///////6/////////38AAAAA////BQAA
AAD///8BAAAAAP///w7////x//////////7///////////7+///8/P///f3///////+/xvX/JBnn
/0I/3/////v/1Nfx/yEd3f81OOb/7fD5//////+Woe//DQDf/2JW4v////3///////////r/////
////fwAAAAD///8FAAAAAP///wEAAAAA////Dv////H//////////v/////9/f///f3////////y
9Pv/iJHq/yYm3/8mC+H/eHvt//////+lrvD/Ihfe/yIX5P++vfX//////5mm6/8YE97/MC7g/9zj
9////////v7/+v////////9/AAAAAP///wUAAAAA////AQAAAAD///8O////8f/////////+/Pz/
///////t8fv/ipTw/zU35f8qFN7/Qx/g/yMb5v/O1Pn//////3F36v8oFOD/JxDj/5GS7v//////
g5jv/x4O4P8rLN//y9v4///////9/v/6/////////38AAAAA////BQAAAAD///8BAAAAAP///w7/
///x//////39//7/////0M72/zo/6f8fDOH/QR7g/0wn4P8ZCeP/jpXy///////4+Pv/REDp/zsb
4P8oEOH/e3ry/////f9nZe3/Kw3i/zEw3v/g5ff///////7+//r/////////fwAAAAD///8FAAAA
AP///wEAAAAA////Dv////H9/f///////sbJ8P8nIuD/Nhfh/00o3/8vFOL/IBXg/4eQ6/////z/
/////8jJ9v8nGeP/SSbf/ywM4/+AdPP////9/0w/7f8vEN//Tkjj//j4/P///////v7/+v//////
//9/AAAAAP///wUAAAAA////AQAAAAD+/v8O/v7/8f/////d5fT+Myvg/0Ad4P86GuD/JBbj/1dT
6P/Ev/P////+//r6//////7/g3/u/ygN4f9MKOD/HA7g/4OH7/////3/TUXt/y0K3/9SYeX//v//
///+///////6/////////38AAAAA////BQAAAAD///8BAAAAAPz8/g78/f/x/////2Zx7f4sEeL/
MBfg/09F6v/Fyu3////6///+///8/P7//////+/y9v88Nt//Oxrg/0gl3/8iEOP/rK7z//////+K
je//EwDi/1hc5P/9//7///////////r/////////fwAAAAD///8FAAAAAP///wEAAAAA6Ob6Dv//
//Hi4Pj/LSPm/iYR3f94euj/+fz+///////9/f///fz///z8////////oqXv/ykU3v9FJOH/PR7g
/y8p4P/i4fj///////f5+/9KRej/LB7i//Ps+P///////v7/+v////////9/AAAAAP///wUAAAAA
////AQAAAADGxfoO////8amr8/8EAeH+iYLn/////f/9/f///f3////////+/v////////L1/P84
QOP/ORnf/0gm4P8rEt//ZXLi/////v/8/P///////+zz9/9iZer/wb/u///////9/f/6////////
/38AAAAA////BQAAAAD+/f8BAAAAAL+4/w7////xgH/0/0BB6v7///v//f3///7+////////////
//z8////////o6nz/xwO4/9HJeD/Px3g/y8p3f/W3vf///////7+///+/v////////v9+//v9vb/
//////////r/////////fwAAAAD///8FAAAAAP39/wEAAAAA1836Dv////GGie7/xMD2/v/////9
/P///////////////////f3//////v9jX+3/LBHh/0on3/8nEeL/nKDp///////9/P//////////
///+/v///f7/////////////////+v////////9/AAAAAP///wUAAAAA/v7/AQAAAAD+9/0O////
8dng7v/4+Pz+//////////////////////7+////////7/L1/zMy5v9AHuH/LxTg/1VW6/////7/
/f3////////////////////////+/v///v7////////////6/////////38AAAAA////BQAAAAD/
//8BAAAAAP///w7////x//////7///7//////////////////////f3////////R1vf/Kx7m/0Yh
3/8lGuP/w8b0///////9/f////////////////////////////////////////////r/////////
fwAAAAD///8FAAAAAP///wEAAAAA/v7/Dv////H+/v///////v/////////////////////9/f//
/////7zJ+P8oGOn/Nxfe/1NW5P////7//v7/////////////////////////////////////////
////////+v////////9/AAAAAP///wUAAAAA////AQAAAAD///8O////8f/////////+////////
//////////////z9////////t8b4/ycY6P8vFNz/mpns///////8/P//////////////////////
///////////////////////////6/////////38AAAAA////BQAAAAD///8BAAAAAP///w7////x
//////////7//////////////////////f3////////Gzvj/Khnn/y8f3P/LzfD///////39/v//
//////////////////////////////////////////////r/////////fwAAAAD///8FAAAAAP//
/wEAAAAA////Dv////H//////////v/////////////////////+/v///////+jp+f8uJef/Ky3g
/+Hq+f///////v7/////////////////////////////////////////////////+v////////9/
AAAAAP///wUAAAAA////AQAAAAD///8O////8f/////////+////////////////////////////
///////+/01G6/9DLeD/9/T5///////+/v//////////////////////////////////////////
///////6/////////38AAAAA////BQAAAAD///8BAAAAAP///w7////x//////////7/////////
//////////////////z8////////iYjw/yom4v/29vj///////7+////////////////////////
//////////////////////////r/////////fwAAAAD///8FAAAAAP///wEAAAAA////Dv////H/
/////////v///////////////////////////f3////////Rz/b/Iivk/+bp+v///////v7/////
////////////////////////////////////////////+v////////9/AAAAAP///wUAAAAA////
AQAAAAD///8O////8f/////////+/////////////////////////////////v7//////v9mW+j/
u7j0///////9/f/////////////////////////////////////////////////6/////////38A
AAAA////BQAAAAD///8BAAAAAP///w7////x//////////7/////////////////////////////
///9/f///////8TI9P+Xnuv///////z9////////////////////////////////////////////
//////r/////////fwAAAAD///8FAAAAAP///wEAAAAA////Dv////H//////////v//////////
////////////////////////////////+/z//8fE7P/19/n/////////////////////////////
////////////////////////+v////////9/AAAAAP///wUAAAAA////AQAAAAD///8O////8f//
///////+/////////////////////////////////////////////v///P39//3+/v//////////
///////////////////////////////////////////6/////////38AAAAA////BQAAAAD///8B
AAAAAP///w7////x//////////7////////////////////////////////////////////////+
/v////////////////////////////////////////////////////////////r/////////fwAA
AAD///8FAAAAAOAAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAA
D+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP
4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAPKAAAABAAAAAgAAAAAQAgAAAAAAAABAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAD///99//////////v////////////////+/v///v7///7+///9/f///v7/////
//3/////////QAAAAAAAAAAA////ff/////////7///////////9/f/////////////+/v//////
//7+///////9/////////0AAAAAAAAAAAP///33/////////+/39///+/v//9/f+/97f+P/R0PX/
6+36/9PU9v/x8f3//////f////////9AAAAAAAAAAAD///99//////39//v9/f///////5OS8f+d
nO//h4jp/6ao8f+4uvb/XVrn//////3+/v///v7/QAAAAAAAAAAA////ff39///////73uP7/3x1
6v8eDuD/2dr5/1xW5/9rYOv/1tv3/x4b3v/j5/r9//////n6/kAAAAAAAAAAAPv7/33/////srHy
+ysW4f8cAN3/mpbw//Dz/f8yHOL/a1rr/6mk9f81JuH/7/P7/f/////7+/5AAAAAAAAAAAD///99
1Nb4/x8J3ftgT+b/xsb1//////+rqPH/IwLd/3hv7P+2svb/Myni//r+/v3//////P3/QAAAAAAA
AAAA////fXJu7f96cur7///////+///5/f7/W0/l/yUF3P+hoe///////3x66//h3/j9//////r6
/kAAAAAAAAAAAPX3/X2ZmvL/+Pj9+/38////////v8D3/ycK4P9XR+P/8/j8///////5+v3/+fr9
/f/////+/v9AAAAAAAAAAAD5+/199fb7//7+//v7+////////42H7v8iCN//xMX3///////8/P//
/f3///////3/////////QAAAAAAAAAAA////ff7+///+/v/7/fz///////9uaO//Tz/j///////+
/v/////////////////9/////////0AAAAAAAAAAAP///33+////////+/z8////////dXDu/3dz
6f///////Pz//////////////////f////////9AAAAAAAAAAAD///99//////////v8/P//////
/6Si8/+MiO3///////z7//////////////////3/////////QAAAAAAAAAAA////ff/////////7
/v7////////h4Pr/kpLv///////9/f/////////////////9/////////0AAAAAAAAAAAP///33/
////////+//////+/////////9DQ9f/3+Pz//////////////////////f////////9AAAAAAAAA
AAD///99//////////v////////////////8/P7//f7+//////////////////////3/////////
QAAAAADAAwAAwAMAAMADAADAAwAAwAMAAMADAADAAwAAwAMAAMADAADAAwAAwAMAAMADAADAAwAA
wAMAAMADAADAAwAA')
	#endregion
	$formAstraAssist.MaximizeBox = $False
	$formAstraAssist.Name = 'formAstraAssist'
	$formAstraAssist.Text = 'Astra Assist'
	$formAstraAssist.add_Load($formAstraAssist_Load)
	#
	# radiobuttonCurrentTime
	#
	$radiobuttonCurrentTime.Checked = $True
	$radiobuttonCurrentTime.Font = 'Microsoft Sans Serif, 10pt'
	$radiobuttonCurrentTime.Location = '291, 49'
	$radiobuttonCurrentTime.Name = 'radiobuttonCurrentTime'
	$radiobuttonCurrentTime.Size = '110, 24'
	$radiobuttonCurrentTime.TabIndex = 20
	$radiobuttonCurrentTime.TabStop = $True
	$radiobuttonCurrentTime.Text = 'Current Time'
	$radiobuttonCurrentTime.UseVisualStyleBackColor = $True
	$radiobuttonCurrentTime.add_CheckedChanged($radiobuttonCurrentTime_CheckedChanged)
	#
	# radiobuttonAlternateTime
	#
	$radiobuttonAlternateTime.Font = 'Microsoft Sans Serif, 10pt'
	$radiobuttonAlternateTime.Location = '401, 49'
	$radiobuttonAlternateTime.Name = 'radiobuttonAlternateTime'
	$radiobuttonAlternateTime.Size = '125, 24'
	$radiobuttonAlternateTime.TabIndex = 19
	$radiobuttonAlternateTime.Text = 'Alternate Time'
	$radiobuttonAlternateTime.UseVisualStyleBackColor = $True
	#
	# labelCurrentNextEventName
	#
	$labelCurrentNextEventName.AutoSize = $True
	$labelCurrentNextEventName.Font = 'Microsoft Sans Serif, 12pt'
	$labelCurrentNextEventName.Location = '25, 268'
	$labelCurrentNextEventName.Name = 'labelCurrentNextEventName'
	$labelCurrentNextEventName.Size = '193, 20'
	$labelCurrentNextEventName.TabIndex = 18
	$labelCurrentNextEventName.Text = 'Current/Next Event Name:'
	#
	# classname
	#
	$classname.Location = '274, 268'
	$classname.Name = 'classname'
	$classname.ReadOnly = $True
	$classname.Size = '235, 20'
	$classname.TabIndex = 17
	#
	# labelTime
	#
	$labelTime.AutoSize = $True
	$labelTime.Font = 'Microsoft Sans Serif, 12pt'
	$labelTime.Location = '439, 74'
	$labelTime.Name = 'labelTime'
	$labelTime.Size = '43, 20'
	$labelTime.TabIndex = 16
	$labelTime.Text = 'Time'
	#
	# labelDate
	#
	$labelDate.AutoSize = $True
	$labelDate.Font = 'Microsoft Sans Serif, 12pt'
	$labelDate.Location = '327, 74'
	$labelDate.Name = 'labelDate'
	$labelDate.Size = '44, 20'
	$labelDate.TabIndex = 15
	$labelDate.Text = 'Date'
	#
	# altdate
	#
	$altdate.Enabled = $False
	$altdate.Font = 'Microsoft Sans Serif, 12pt'
	$altdate.ForeColor = 'WindowText'
	$altdate.Location = '303, 97'
	$altdate.MinimumSize = '100, 26'
	$altdate.Multiline = $True
	$altdate.Name = 'altdate'
	$altdate.Size = '100, 26'
	$altdate.TabIndex = 3
	$altdate.TextAlign = 'Center'
	$tooltip1.SetToolTip($altdate, 'Enter Date in following format:
YYYY-MM-DD')
	#
	# alttime
	#
	$alttime.Enabled = $False
	$alttime.Font = 'Microsoft Sans Serif, 12pt'
	$alttime.ForeColor = 'WindowText'
	$alttime.Location = '409, 97'
	$alttime.Multiline = $True
	$alttime.Name = 'alttime'
	$alttime.Size = '100, 26'
	$alttime.TabIndex = 4
	$alttime.TextAlign = 'Center'
	$tooltip1.SetToolTip($alttime, 'Enter Time in following format:
HH:MM:(AM or PM)

')
	#
	# labelAlternateTime
	#
	$labelAlternateTime.AutoSize = $True
	$labelAlternateTime.Font = 'Microsoft Sans Serif, 14pt'
	$labelAlternateTime.Location = '338, 20'
	$labelAlternateTime.Name = 'labelAlternateTime'
	$labelAlternateTime.Size = '132, 24'
	$labelAlternateTime.TabIndex = 11
	$labelAlternateTime.Text = 'Alternate Time'
	#
	# classaftertime
	#
	$classaftertime.Location = '274, 234'
	$classaftertime.Name = 'classaftertime'
	$classaftertime.ReadOnly = $True
	$classaftertime.Size = '235, 20'
	$classaftertime.TabIndex = 10
	#
	# classafter
	#
	$classafter.Location = '274, 202'
	$classafter.Name = 'classafter'
	$classafter.ReadOnly = $True
	$classafter.Size = '235, 20'
	$classafter.TabIndex = 9
	#
	# classendtime
	#
	$classendtime.Location = '274, 171'
	$classendtime.Name = 'classendtime'
	$classendtime.ReadOnly = $True
	$classendtime.Size = '235, 20'
	$classendtime.TabIndex = 8
	#
	# roomavailability
	#
	$roomavailability.Location = '274, 139'
	$roomavailability.Name = 'roomavailability'
	$roomavailability.ReadOnly = $True
	$roomavailability.Size = '235, 20'
	$roomavailability.TabIndex = 7
	#
	# labelNextEventStartsAt
	#
	$labelNextEventStartsAt.AutoSize = $True
	$labelNextEventStartsAt.Font = 'Microsoft Sans Serif, 12pt'
	$labelNextEventStartsAt.Location = '25, 234'
	$labelNextEventStartsAt.Name = 'labelNextEventStartsAt'
	$labelNextEventStartsAt.Size = '155, 20'
	$labelNextEventStartsAt.TabIndex = 6
	$labelNextEventStartsAt.Text = 'Next Event Starts at:'
	#
	# labelCurrentEventEndsAt
	#
	$labelCurrentEventEndsAt.AutoSize = $True
	$labelCurrentEventEndsAt.Font = 'Microsoft Sans Serif, 12pt'
	$labelCurrentEventEndsAt.Location = '25, 171'
	$labelCurrentEventEndsAt.Name = 'labelCurrentEventEndsAt'
	$labelCurrentEventEndsAt.Size = '170, 20'
	$labelCurrentEventEndsAt.TabIndex = 5
	$labelCurrentEventEndsAt.Text = 'Current Event Ends at:'
	#
	# labelEventScheduledAfterC
	#
	$labelEventScheduledAfterC.AutoSize = $True
	$labelEventScheduledAfterC.Font = 'Microsoft Sans Serif, 12pt'
	$labelEventScheduledAfterC.Location = '25, 202'
	$labelEventScheduledAfterC.Name = 'labelEventScheduledAfterC'
	$labelEventScheduledAfterC.Size = '230, 20'
	$labelEventScheduledAfterC.TabIndex = 4
	$labelEventScheduledAfterC.Text = 'Event Scheduled After Current:'
	#
	# labelRoomAvailability
	#
	$labelRoomAvailability.AutoSize = $True
	$labelRoomAvailability.Font = 'Microsoft Sans Serif, 12pt'
	$labelRoomAvailability.Location = '25, 139'
	$labelRoomAvailability.Name = 'labelRoomAvailability'
	$labelRoomAvailability.Size = '132, 20'
	$labelRoomAvailability.TabIndex = 3
	$labelRoomAvailability.Text = 'Room Availability:'
	#
	# labelRoomName
	#
	$labelRoomName.AutoSize = $True
	$labelRoomName.Font = 'Microsoft Sans Serif, 14pt'
	$labelRoomName.Location = '30, 20'
	$labelRoomName.Name = 'labelRoomName'
	$labelRoomName.Size = '117, 24'
	$labelRoomName.TabIndex = 2
	$labelRoomName.Text = 'Room Name'
	#
	# roomname
	#
	$roomname.BackColor = 'Window'
	$roomname.Font = 'Microsoft Sans Serif, 12pt'
	$roomname.ForeColor = 'WindowText'
	$roomname.Location = '23, 47'
	$roomname.Name = 'roomname'
	$roomname.Size = '132, 26'
	$roomname.TabIndex = 0
	$roomname.TextAlign = 'Center'
	$tooltip1.SetToolTip($roomname, 'Enter the building code first, then the room number.
Ex. DSC 251 = David Straz Center Room 251
')
	$roomname.add_TextChanged($roomname_TextChanged)
	#
	# buttonCheckRoom
	#
	$buttonCheckRoom.Enabled = $False
	$buttonCheckRoom.Font = 'Microsoft Sans Serif, 12pt'
	$buttonCheckRoom.Location = '161, 40'
	$buttonCheckRoom.Name = 'buttonCheckRoom'
	$buttonCheckRoom.Size = '124, 41'
	$buttonCheckRoom.TabIndex = 1
	$buttonCheckRoom.Text = 'Check Room'
	$buttonCheckRoom.UseVisualStyleBackColor = $True
	$buttonCheckRoom.add_Click($buttonCheckRoom_Click)
	#
	# tooltip1
	#
	$tooltip1.AutoPopDelay = 5000
	$tooltip1.InitialDelay = 200
	$tooltip1.IsBalloon = $True
	$tooltip1.ReshowDelay = 100
	$formAstraAssist.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formAstraAssist.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formAstraAssist.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formAstraAssist.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formAstraAssist.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formAstraAssist.ShowDialog()

}
#endregion Source: MainForm.psf

#Start the application
Main ($CommandLine)
